from pathlib import Path
from typing import Protocol

from app.models import Job


class JobStore(Protocol):
    def create_job(self, job: Job) -> Job: ...

    def get_job(self, job_id: str) -> Job | None: ...

    def update_job(self, job: Job) -> Job: ...

    def save_audio(self, job_id: str, source_name: str, content: bytes) -> Path: ...

    def save_transcript(self, job_id: str, transcript: str, vtt: str | None = None) -> Path: ...

    def save_summary(self, job_id: str, summary: dict, markdown: str) -> tuple[Path, Path]: ...

    def read_transcript(self, job_id: str) -> str | None: ...

    def read_transcript_vtt(self, job_id: str) -> str | None: ...

    def read_summary(self, job_id: str) -> tuple[dict, str] | None: ...

    def job_audio_path(self, job_id: str) -> Path | None: ...
